orgabat_game:
    resource: "@OrgabatGameBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@OrgabatGameBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
