security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_APPRENTICE: ROLE_USER
        ROLE_TRAINER:  ROLE_APPRENTICE
        ROLE_ADMIN:       ROLE_TRAINER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                success_handler: orgabat.security.login_handler
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /deconnexion
                target: /
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/rubriques, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/classes$, role: ROLE_TRAINER }
        - { path: ^/admin/modifier_infos$, role: ROLE_TRAINER }
        - { path: ^/admin/classe$, role: ROLE_TRAINER }
        - { path: ^/admin/apprentis, role: ROLE_TRAINER }
        - { path: ^/admin/apprenti, role: ROLE_TRAINER }
        - { path: ^/admin/apprentis/statistiques, role: ROLE_TRAINER }
        - { path: ^/admin/formateurs$, role: ROLE_ADMIN }
        - { path: ^/admin/apprentis/exporter, role: ROLE_ADMIN }
        - { path: ^/admin/apprentis/importer, role: ROLE_ADMIN }
        - { path: ^/admin/formateurs/exporter, role: ROLE_ADMIN }
        - { path: ^/admin/formateurs/importer, role: ROLE_ADMIN }
        - { path: ^/admin/classes/exporter, role: ROLE_ADMIN }
        - { path: ^/admin/classes/importer, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_TRAINER }
