security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_APPRENTICE: ROLE_USER
        ROLE_TRAINER:  ROLE_APPRENTICE
        ROLE_ADMIN:       ROLE_TRAINER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                success_handler: orgabat.security.login_handler
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /deconnexion
                target: /
            anonymous:    true
