<?php

namespace Orgabat\GameBundle\Repository;

/**
 * CurveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurveRepository extends \Doctrine\ORM\EntityRepository
{
}
