<?php

namespace Orgabat\GameBundle\Repository;

use Orgabat\GameBundle\Entity\Category;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExercisesOfCategory(Category $category)
    {
        return $this->createQueryBuilder('e')
            ->join('e.category', 'cat')
            ->addSelect('cat')
            ->where('e.category = :category')
            ->setParameter('category', $category)
            ->orderBy('e.id', 'asc')
            ->getQuery()
            ->getResult()
        ;
    }
}
