<?php

namespace Orgabat\GameBundle\Repository;

/**
 * HistoricalRealisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
