<?php

namespace Orgabat\GameBundle\Repository;

/**
 * HistoricalCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricalCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
