<?php

namespace Orgabat\GameBundle\Repository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWithTrainersAndApprentices() {
        return $this->createQueryBuilder('s')
            ->leftJoin('s.trainers', 't')
            ->leftJoin('s.apprentices','a' )
            ->addSelect('t')
            ->addSelect('a')
            ->orderBy('s.id', 'asc')
            ->getQuery()
            ->getResult()
        ;
    }
}
