# DefaultController

default_rules:
    path:    /
    defaults: { _controller: OrgabatGameBundle:Default:showRules }

default_category:
    path:    /rubriques
    defaults: { _controller: OrgabatGameBundle:Default:showMenu }

default_games:
    path:    /rubriques/{category_id}
    defaults: { _controller: OrgabatGameBundle:Default:showGames }
    requirements:
        id:   \d+

default_admin_board:
    path:   /admin
    defaults:  { _controller: OrgabatGameBundle:Default:showAdmin }

# APIGameController

apigame_score:
    path:     /api/score
    defaults: { _controller: OrgabatGameBundle:APIGame:score }
    requirements:
      sf_method: 'post'

# GameController

game_game:
    path:     /jeu/{id}
    defaults: { _controller: OrgabatGameBundle:Game:game }
    requirements:
        id:   \d+

# AdminController

admin_create_user:
    path:    /creation-utilisateur
    defaults: { _controller: OrgabatGameBundle:Admin:createUser}
