# DefaultController

default_rules:
    path:    /
    defaults: { _controller: OrgabatGameBundle:Default:showRules }

default_category:
    path:    /rubriques
    defaults: { _controller: OrgabatGameBundle:Default:showMenu }

default_games:
    path:    /rubriques/{category_id}
    defaults: { _controller: OrgabatGameBundle:Default:showGames }
    requirements:
        id:   \d+

default_admin_board:
    path:   /admin
    defaults:  { _controller: OrgabatGameBundle:Default:showAdmin }

# APIGameController

apigame_score:
    path:     /api/score
    defaults: { _controller: OrgabatGameBundle:APIGame:score }
    requirements:
      sf_method: 'post'

# GameController

game_game:
    path:     /jeu/{id}
    defaults: { _controller: OrgabatGameBundle:Game:game }
    requirements:
        id:   \d+

# AdminController

# User
admin_create_user:
    path:    /admin/creerApprenti
    defaults: { _controller: OrgabatGameBundle:Admin:createUser}

admin_alter_user:
    path:    /admin/modifierApprenti/{id}
    defaults: { _controller: OrgabatGameBundle:Admin:editUser}

admin_remove_user:
    path:    /admin/supprimerApprenti/{id}
    defaults: { _controller: OrgabatGameBundle:Admin:deleteUser}

admin_export_user:
    path:   /admin/exporterApprentis
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllApprentices}

admin_export_userBySection:
    path:   /admin/exporterApprentisParClasse/{id}
    defaults: { _controller: OrgabatGameBundle:Admin:exportApprenticesBySection}

admin_import_user:
    path:   /admin/importerApprentis
    defaults: { _controller: OrgabatGameBundle:Admin:importApprentices}


# Trainer

admin_create_trainer:
    path:    /admin/creerEnseignant
    defaults: { _controller: OrgabatGameBundle:Admin:createTrainer}

admin_alter_trainer:
    path:    /admin/modifierEnseignant/{id}
    defaults: { _controller: OrgabatGameBundle:Admin:editTrainer}

admin_remove_trainer:
    path:    /admin/supprimerEnseignant/{id}
    defaults: { _controller: OrgabatGameBundle:Admin:deleteTrainer}

admin_export_trainer:
    path:   /admin/exporterEnseignants
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllTrainers}

admin_export_trainerBySection:
    path:   /admin/exporterEnseignantsParClasse/{id}
    defaults: { _controller: OrgabatGameBundle:Admin:exportTrainersBySection}

admin_import_trainer:
    path:   /admin/importerEnseignants
    defaults: { _controller: OrgabatGameBundle:Admin:importTrainers}

# Section
admin_create_section:
    path:    /admin/creerClasse
    defaults: { _controller: OrgabatGameBundle:Admin:createSection}

admin_alter_section:
    path:    /admin/modifierClasse/{id}
    defaults: { _controller: OrgabatGameBundle:Admin:editSection}

admin_remove_section:
    path:    /admin/supprimerClasse/{id}
    defaults: { _controller: OrgabatGameBundle:Admin:deleteSection}

admin_export_section:
    path:   /admin/exporterClasses
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllSections}

admin_import_section:
    path:   /admin/importerClasses
    defaults: { _controller: OrgabatGameBundle:Admin:importSections}
