# DefaultController

default_rules:
    path:    /
    defaults: { _controller: OrgabatGameBundle:Default:showRules }

default_identification:
    path:    /identification
    defaults: { _controller: OrgabatGameBundle:Default:showConnectionFormUser }

default_category:
    path:    /rubriques
    defaults: { _controller: OrgabatGameBundle:Default:showMenu }

default_admin_board:
    path:   /admin
    defaults:  { _controller: OrgabatGameBundle:Default:showAdmin }

# GameController

game_game:
    path:     /jeu/{id}
    defaults: { _controller: OrgabatGameBundle:Game:game }
    requirements:
        id:   \d+

# UserController

user_admin_creation:
    path:    /admin/creer
    defaults: { _controller: OrgabatGameBundle:User:new }

user_login:
    path:    /login
    defaults: { _controller: OrgabatGameBundle:User:login }

user_check:
    path:    /verification-identifiants
    defaults: { _controller: OrgabatGameBundle:User:check }

user_logout:
    path:    /deconnexion
    defaults: { _controller: OrgabatGameBundle:User:logout }

# AdminController

admin_create_user:
    path:    /creation-utilisateur
    defaults: { _controller: OrgabatGameBundle:Admin:createUser}

