# DefaultController

default_rules:
    path:    /
    defaults: { _controller: OrgabatGameBundle:Default:showRules }

default_category:
    path:    /rubriques
    defaults: { _controller: OrgabatGameBundle:Default:showMenu }

default_games:
    path:    /rubriques/{category_id}
    defaults: { _controller: OrgabatGameBundle:Default:showGames }
    requirements:
        category_id:   \d+

default_sections:
    path:   /admin/classes
    defaults:  { _controller: OrgabatGameBundle:Default:showSections }

default_editinfos:
    path:   /admin/modifier_infos
    defaults:  { _controller: OrgabatGameBundle:Default:showEditInfos }

default_admin_board:
    path:   /admin/
    defaults:  { _controller: OrgabatGameBundle:Default:showAdmin }



# APIGameController

apigame_score:
    path:     /api/score
    defaults: { _controller: OrgabatGameBundle:APIGame:score }
    requirements:
      sf_method: 'post'

# GameController

game_game:
    path:     /jeu/{id}
    defaults: { _controller: OrgabatGameBundle:Game:game }
    requirements:
        id:   \d+

# AdminController

# Apprentice
admin_create_apprentice:
    path:    /admin/apprenti/creer
    defaults: { _controller: OrgabatGameBundle:Admin:createApprentice}

admin_edit_apprentice:
    path:    /admin/apprenti/{apprentice_id}/modifier
    defaults: { _controller: OrgabatGameBundle:Admin:editApprentice}
    requirements:
        apprentice_id: \d+

admin_remove_apprentice:
    path:    /admin/apprenti/{user_id}/supprimer
    defaults: { _controller: OrgabatGameBundle:Admin:deleteUser}
    requirements:
        user_id: \d+

admin_remove_user:
    path: /admin/utilisateur/{user_id}/supprimer
    defaults: { _controller: OrgabatGameBundle:Admin:deleteUser}
    requirements:
        user_id: \d+

admin_export_user:
    path:   /admin/apprentis/exporter
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllApprentices}

admin_export_userBySection:
    path:   /admin/apprentis/classe/{section_id}/exporter
    defaults: { _controller: OrgabatGameBundle:Admin:exportApprenticesBySection}
    requirements:
        section_id: \d+

admin_import_user:
    path:   /admin/apprentis/importer
    defaults: { _controller: OrgabatGameBundle:Admin:importApprentices}

# Trainer

admin_create_trainer:
    path:    /admin/enseignant/creer
    defaults: { _controller: OrgabatGameBundle:Admin:createTrainer}

admin_edit_trainer:
    path:    /admin/enseignant/{trainer_id}/modifier
    defaults: { _controller: OrgabatGameBundle:Admin:editTrainer}
    requirements:
        trainer_id: \d+


admin_remove_trainer:
    path:    /admin/enseignant/{user_id}/supprimer
    defaults: { _controller: OrgabatGameBundle:Admin:deleteUser}
    requirements:
        user_id: \d+

admin_export_trainer:
    path:   /admin/enseignants/exporter
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllTrainers}

admin_import_trainer:
    path:   /admin/enseignants/importer
    defaults: { _controller: OrgabatGameBundle:Admin:importTrainers}

# Section
admin_create_section:
    path:    /admin/classe/creer
    defaults: { _controller: OrgabatGameBundle:Admin:createSection}

admin_edit_section:
    path:    /admin/classe/{section_id}/modifier
    defaults: { _controller: OrgabatGameBundle:Admin:editSection}
    requirements:
        section_id: \d+

admin_remove_section:
    path:    /admin/classe/{section_id}/supprimer
    defaults: { _controller: OrgabatGameBundle:Admin:deleteSection}
    requirements:
        section_id: \d+

admin_export_section:
    path:   /admin/classes/exporter
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllSections}

admin_import_section:
    path:   /admin/classes/importer
    defaults: { _controller: OrgabatGameBundle:Admin:importSections}
