# DefaultController

default_rules:
    path:    /
    defaults: { _controller: OrgabatGameBundle:Default:showRules }

default_category:
    path:    /rubriques
    defaults: { _controller: OrgabatGameBundle:Default:showMenu }

default_games:
    path:    /rubriques/{category_id}
    defaults: { _controller: OrgabatGameBundle:Default:showGames }
    requirements:
        id:   \d+

default_sections:
    path:   /admin/classes
    defaults:  { _controller: OrgabatGameBundle:Default:showSections }

default_editinfos:
    path:   /admin/modifier_infos
    defaults:  { _controller: OrgabatGameBundle:Default:showEditInfos }

default_admin_board:
    path:   /admin
    defaults:  { _controller: OrgabatGameBundle:Default:showAdmin }



# APIGameController

apigame_score:
    path:     /api/score
    defaults: { _controller: OrgabatGameBundle:APIGame:score }
    requirements:
      sf_method: 'post'

# GameController

game_game:
    path:     /jeu/{id}
    defaults: { _controller: OrgabatGameBundle:Game:game }
    requirements:
        id:   \d+

# AdminController

# User
admin_create_user:
    path:    /admin/apprenti/creer
    defaults: { _controller: OrgabatGameBundle:Admin:createUser}

admin_alter_user:
    path:    /admin/apprenti/{id}/modifier
    defaults: { _controller: OrgabatGameBundle:Admin:editUser}

admin_remove_user:
    path:    /admin/apprenti/{id}/supprimer
    defaults: { _controller: OrgabatGameBundle:Admin:deleteUser}

admin_export_user:
    path:   /admin/apprentis/exporter
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllApprentices}

admin_export_userBySection:
    path:   /admin/apprentis/classe/{id}/exporter
    defaults: { _controller: OrgabatGameBundle:Admin:exportApprenticesBySection}

admin_import_user:
    path:   /admin/apprentis/importer
    defaults: { _controller: OrgabatGameBundle:Admin:importApprentices}


# Trainer

admin_create_trainer:
    path:    /admin/enseignant/creer
    defaults: { _controller: OrgabatGameBundle:Admin:createTrainer}

admin_alter_trainer:
    path:    /admin/enseignant/{id}/modifier
    defaults: { _controller: OrgabatGameBundle:Admin:editTrainer}

admin_remove_trainer:
    path:    /admin/enseignant/{id}/supprimer
    defaults: { _controller: OrgabatGameBundle:Admin:deleteTrainer}

admin_export_trainer:
    path:   /admin/enseignants/exporter
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllTrainers}

admin_import_trainer:
    path:   /admin/enseignants/importer
    defaults: { _controller: OrgabatGameBundle:Admin:importTrainers}

# Section
admin_create_section:
    path:    /admin/classe/creer
    defaults: { _controller: OrgabatGameBundle:Admin:createSection}

admin_alter_section:
    path:    /admin/classe/{id}/modifier
    defaults: { _controller: OrgabatGameBundle:Admin:editSection}

admin_remove_section:
    path:    /admin/classe/{id}/supprimer
    defaults: { _controller: OrgabatGameBundle:Admin:deleteSection}

admin_export_section:
    path:   /admin/classes/exporter
    defaults: { _controller: OrgabatGameBundle:Admin:exportAllSections}

admin_import_section:
    path:   /admin/classes/importer
    defaults: { _controller: OrgabatGameBundle:Admin:importSections}

# PDF
user_get_infos_pdf:
    path:   /statistiques
    defaults: { _controller: OrgabatGameBundle:Default:getUserInfosUsingPDF}

admin_get_users_infos_pdf:
    path:   /admin/apprentis/statistiques
    defaults: { _controller: OrgabatGameBundle:Default:getAllUsersInfosUsingPDF}